### ISSUE TITLE
sveltekit usage

### ISSUE THREAD

**Issue by schmurfy** [andrewjk/svelte-toolkit#3]
I really like this library and wanted to try using it with sveltekit but I failed, when importing a component it fails at:
```javascript
import Toolkit from './src/base/Toolkit/Toolkit';
```

it fails to find this exact file and does not try to load the `Toolkit.svelte` file, I imagine there is a way somewhere to configure this but I have no f***ing clue where... Each time I try to do anything with frontend dev I end up depressing even more in its curent state...

Do you have any idea on how this work with sveltekit ?

**Comment by schmurfy** [comment]
I can't make it work either without sveltekit, I tried:

```bash
npx degit sveltejs/template my-svelte-project
cd my-svelte-project
yarn add -D svelte-toolkit
```

and then adding `	import { Button } from "svelte-toolkit";`
and `<Button>Click me</Button>`  but it fails:

```javascript
Could not resolve './src/icons/ArrowLeft' from node_modules/svelte-toolkit/main.js
```

**Comment by andrewjk** [comment]
Hi Julien, sorry about that.  You're correct that SvelteKit (or more accurately, Vite, which SvelteKit uses to run its dev server) doesn't know how to load .svelte files from node_modules out of the box and needs some config.  I added that config to the template that I use for my own projects, made a note to figure out how to remove it and then got distracted.

Anyway, I've released a new version of svelte-toolkit that shouldn't need any config.  You should be able to make a new SvelteKit project, add svelte-toolkit as a dev dependency and then use svelte-toolkit components in your svelte components.

Just in case you run into this problem again in the future, the config that you need to use to get Vite to recognize .svelte files in SvelteKit sites goes in svelte.config.js and should look something like this:

```javascript
 const config = {
  kit: {
    vite: (() => ({
      resolve: {
        // Add .svelte to the default extensions to resolve svelte files in node_modules
        extensions: ['.mjs', '.js', '.ts', '.json', '.svelte']
      }
    }))
  }
};
```

**Comment by schmurfy** [comment]
thanks a lot, I will test that this week-end  👍

**Comment by schmurfy** [comment]
it works !
